NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('news.urls')),
]

news/urls.py
from django.urls import path
from .views import PostList, PostDetail, PostCreate, PostUpdate, PostDelete

app_name = 'news'

urlpatterns = [
    path('', PostList.as_view(), name='posts'),
    path('post/<int:pk>/', PostDetail.as_view(), name='post_detail'),
    path('create/', PostCreate.as_view(), name='post_create'),
    path('update/<int:pk>', PostUpdate.as_view(), name='post_update'),
    path('delete/<int:pk>', PostDelete.as_view(), name='post_delete')
]

accounts/models.py
from django.db import models

# Create your models here.

news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models  import Sum


class Author(models.Model):
    def __str__(self):
        return self.authorUser.username

    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    ratingAuthor = models.SmallIntegerField(default=0)

    def update_rating(self):
        postRat = self.post_set.all().aggregate(postRating=Sum('rating'))
        pRat = 0
        pRat += postRat.get('postRating')

        commentRat = self.authorUser.comment_set.all().aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commentRating')

        self.ratingAuthor = pRat * 3 + cRat
        self.save()


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOICES = (
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья'),
    )
    categoryType = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=ARTICLE)
    dateCreation = models.DateTimeField(auto_now_add=True)
    postCategory = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=128)
    text = models.TextField()
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[0:20] + '...'

    def get_absolute_url(self):  # добавим абсолютный путь, чтобы после создания нас перебрасывало на страницу с товаром
        return f'/posts/post/{self.id}'


class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dateCreation = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def __str__(self):
        return self.commentUser.username

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

news/forms.py
from django.forms import ModelForm
from .models import Post
from django import forms


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'text', 'categoryType', 'author']
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter post title'
            }),
            'text': forms.Textarea(attrs={
                'class': 'form-control',
            }),
            'categoryType': forms.Select(attrs={
                'class': 'form-control',
            }),
            'author': forms.Select(attrs={
                'class': 'form-control',
            })
        }

accounts/views.py
from django.shortcuts import render

# Create your views here.

news/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DeleteView, CreateView, UpdateView, DetailView

from .models import Post
from .filters import PostFilter
from .forms import PostForm


class PostList(ListView):
    model = Post
    template_name = 'news/posts.html'
    context_object_name = 'posts'
    ordering = ['-rating']
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = PostFilter(self.request.GET, queryset=self.get_queryset())
        context['choices'] = Post.CATEGORY_CHOICES
        context['form'] = PostForm()
        return context

    def post(self, request, *args, **kwargs):
        form = PostForm(request.POST)
        if form.is_valid():
            form.save()
        return super().get(request, *args, **kwargs)


class PostDetail(DetailView):
    template_name = 'news/post.html'
    queryset = Post.objects.all()


class PostCreate(CreateView):
    template_name = 'news/post_create.html'
    form_class = PostForm


class PostUpdate(UpdateView):
    template_name = 'news/post_create.html'
    form_class = PostForm

    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        return Post.objects.get(pk=id)


class PostDelete(DeleteView):
    template_name = 'news/post_delete.html'
    queryset = Post.objects.all()
    success_url = reverse_lazy('news:posts')

news/templates/news/parts/paginator.html
{% if is_paginated %}
    <!-- Если доступна предыдущая страница, то даём ссылку на неё и самую первую страницу -->
   {% if page_obj.has_previous %}
       <a href="?page=1">First</a>
       <a href="?page={{ page_obj.previous_page_number }}"><<<</a>
   {% endif %}
   <!-- Показываем только текущую страницу и ближайшие к ней, чтобы список не тянулся и не захламлял страницу -->
   {% for num in page_obj.paginator.page_range %}
       {% if page_obj.number == num %}
           <a>{{ num }}</a>
       {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
           <a href="?page={{ num }}">{{ num }}</a>
       {% endif %}
   {% endfor %}
   <!-- Если есть следующая страница, то даём ссылку на неё и на самую последнюю страницу -->
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">>>></a>
       <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
   {% endif %}
{% endif %}

news/templates/news/post.html

{% extends 'layout/base.html' %}
{% load custom_filters %}

{% block title %}
    Post
{% endblock title %}
<!-- В контенте на странице мы выводим сам продукт, первичный ключ которого был передан в адрес -->
{% block content %}
    <h1>{{ post.title|censor_text }}</h1>
    <h4>{{ post.dateCreation|date:'d M Y' }}</h4>
    <hr>
    <p>{{ post.text|censor_text }}</p>
    <p>{{ post.author.authorUser }}</p>
{% endblock content %}

news/templates/news/post_create.html
{% extends 'layout/base.html' %}


{% block title %}
Post create
{% endblock title %}

{% block content %}

<h3>Post Information</h3>

<form method="POST">
 {% csrf_token %}
 {{ form }}
   <!-- Теперь нам нужна только готовая форма и кнопка -->
   <input class="btn btn-success" type="submit" value="Add">
</form>

{% endblock content %}

news/templates/news/post_delete.html
{% extends 'layout/base.html' %}

{% block title %}
Post delete
{% endblock title %}

{% block content %}

<h3>Delete this post?</h3>
<div class="card">
 <div class="card-header">
   <h3>
     {{ post.title }}
   </h3>
   <div>
     Text: <span class="badge bg-info">{{ post.text }}</span>
     Date: <span class="badge bg-info">{{ post.dateCreation|date:'d M Y' }}</span>
   </div>
 </div>
 <div class="card-body">
   {{ post.author.authorUser }}
 </div>
</div>
<form method="POST">
 {% csrf_token %}
   <input class="btn btn-success" type="submit" value="Delete">
</form>

{% endblock content %}

news/templates/news/posts.html
{% extends 'layout/base.html' %}
{% load custom_filters %}

{% block title %}
    Posts
{% endblock title %}

{% block content %}
    <h1>Все посты</h1>
    <h4>Количество постов {{ filter.qs|length }}</h4>
    <hr>
    {% if posts %}

        <form method="GET">
            {{ filter.form }}
            <input class="btn btn-primary" type="submit" value="Найти">
        </form>

        <table>
            <tr>
                <td>
                    Заголовок
                </td>
                <td>
                    Дата публикации
                </td>
                <td>
                    Текст
                </td>
                <td scope="col">
                    Действия
                </td>
            </tr>
        {% for post in filter.qs %}
            <tr>
                <td>
                    <a href="{% url 'news:post_detail' post.id %}">{{ post.title|censor_text }}</a>
                </td>
                <td>
                    {{ post.dateCreation|date:'d M Y' }}
                </td>
                <td>
                    {{ post.text|truncatechars:50|censor_text }}
                </td>
                <td>
                   <a href="{% url 'news:post_update' post.id %}">
                       Update
                   </a>
                   <a href="{% url 'news:post_delete' post.id %}">
                       Delete
                   </a>
                </td>
            </tr>
        {% endfor %}
        </table>

        {% include 'news/parts/paginator.html' %}

    {% else %}
        <h2>Постов нет</h2>
    {% endif %}

{% endblock content %}

templates/layout/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="assets/css/style.css">
<script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

<title>
{% block title %}
{% endblock title %}
</title>
</head>
<body>
{% include './parts/header.html' %}
<div class="container">
 {% block content %}
 {% endblock content %}
</div>

{% include './parts/footer.html' %}
</body>
</html>

templates/layout/parts/footer.html
<footer class="footer mt-auto py-3 bg-light">
 <div class="container">
   <span class="text-muted">Place sticky footer content here.</span>
 </div>
</footer>

templates/layout/parts/header.html
<header class="p-3 text-bg-dark">
 <div class="container">
   <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
     <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
       <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
     </a>

     <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
       <li><a href="#" class="nav-link px-2 text-secondary">Home</a></li>
       <li><a href="#" class="nav-link px-2 text-white">Features</a></li>
       <li><a href="#" class="nav-link px-2 text-white">Pricing</a></li>
       <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
       <li><a href="#" class="nav-link px-2 text-white">About</a></li>
     </ul>

     <div class="text-end">
       <button type="button" class="btn btn-outline-light me-2">Login</button>
       <button type="button" class="btn btn-warning">Sign-up</button>
     </div>
   </div>
 </div>
</header>